In [1]:
import numpy as np

In [4]:
#Ex_5.2
a = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])
print(a)
np.linalg.det(a)


[[1 2 3]
 [4 0 6]
 [7 8 9]]


59.999999999999986

In [6]:
#Ex_5.3_1
a = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])
p = np.linalg.inv(a)
print(a)
print(p)
np.dot(a, p)

[[1 2 3]
 [4 0 6]
 [7 8 9]]
[[-0.8         0.1         0.2       ]
 [ 0.1        -0.2         0.1       ]
 [ 0.53333333  0.1        -0.13333333]]


array([[ 1.00000000e+00,  0.00000000e+00,  5.55111512e-17],
       [-4.44089210e-16,  1.00000000e+00,  1.11022302e-16],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

In [12]:
#Ex_5.3_2
a = np.array([[1, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]])
np.linalg.matrix_rank(a, 0.0001)

1

In [13]:
#Ex_5.4
a = np.array([1, 5], float)
b = np.array([2, 8], float)
np.inner(a, b)


42.0

In [14]:
#Ex_5.5
a = np.array([1, 5, 0], float)
b = np.array([2, 8, 7], float)
c = np.array([7, 1.5, 3], float)
np.linalg.det([a,b,c])

228.50000000000009